### ISSUE TITLE
Bug: Unable to build packages - sync repos first

### ISSUE THREAD

**Issue by CommanderRedYT** [Lukas-Heiligenbrunner/AURCache#14]
Hi, I just installed this software and I got this error for every package:

```
==> Making package: python-smart-prom-next 0.0.8-1 (Tue Jun 25 07:31:37 2024)
warning: database file for 'repo' does not exist (use '-Sy' to download)
==> Checking runtime dependencies...
warning: database file for 'repo' does not exist (use '-Sy' to download)
==> Installing missing dependencies...
warning: database file for 'repo' does not exist (use '-Sy' to download)
error: failed to prepare transaction (could not find database)
==> ERROR: 'pacman' failed to install missing dependencies.
  -> smartmontools
==> Checking buildtime dependencies...
warning: database file for 'repo' does not exist (use '-Sy' to download)
==> Installing missing dependencies...
warning: database file for 'repo' does not exist (use '-Sy' to download)
error: failed to prepare transaction (could not find database)
==> ERROR: 'pacman' failed to install missing dependencies.
==> Missing dependencies:
  -> python-setuptools
warning: database file for 'repo' does not exist (use '-Sy' to download)
==> ERROR: Could not resolve all dependencies.
```

**Comment by CommanderRedYT** [comment]
My workaround for now is to comment out "localhost:8080" inside the pacman.conf inside the docker container.

**Comment by CommanderRedYT** [comment]
It seems that `pacman -Sy` fails until the first package was build successfully. After that, adding the `localhost:8080` repo again works.

**Comment by Lukas-Heiligenbrunner** [comment]
Hey, thanks for your contribution!
Actually on first init I create a empty database file here
https://github.com/Lukas-Heiligenbrunner/AURCache/blob/master/backend/src/main.rs#L71
so it should work, but I'll have a  look why not!

**Comment by tjaartvdwalt** [comment]
I had the same issue running the latest docker build, worked around it by manually creating the database file in the `repo` directory.

```bash
touch repo.db.tar.gz
ln -s custom.db repo.db.tar.gz
```

@Lukas-Heiligenbrunner thank you for creating this project, I have been searching for an AUR build server for a while, and this looks amazing!

**Comment by Lukas-Heiligenbrunner** [comment]
@tjaartvdwalt  Thanks for using my project! 
I've redesigned the build process in #19 quite a bit. Every build job is now executed inside an isolated docker container. You can choose between dind or spawning container jobs on host docker. Please have a look at the updated readme. 
(you either need to make the container privileged or add docker socket and a volume)

Moreover in the future I plan to make the database design a bit simpler to remove versions.  Since pacman only supports downloading the latest version of a package (as far as i know)  it doesn't make sense to keep older package versions in the repo. Stay tuned for a db migration ;)
